title: Your Blog Title
author: Your Name
base_url: https://example.com
disqus_shortname: 
cloudfront_distribution_id: 
posts_per_page: 10
profile_image: /images/your_photo.jpg
bio: I short biography about you. Who are you? What are your hobbies?
hero_image: 
hero_subtitle: A subtitle to describe your blog (update in config.yaml)
